/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useRef, useEffect } from 'react';
import { 
  Stethoscope, 
  Upload, 
  FileText, 
  Clock, 
  AlertCircle, 
  CheckCircle2, 
  Copy, 
  Printer, 
  Languages, 
  User,
  ArrowRight,
  ShieldCheck,
  Zap,
  Share2,
  Loader2,
  Calendar,
  Info,
  ListTodo,
  AlertTriangle,
  Check,
  Lock,
  LogOut,
  Settings,
  Activity,
  Heart,
  ShieldAlert,
  RefreshCw,
  Search,
  Moon,
  Sun,
  BrainCircuit,
  Pill,
  Plus,
  ChevronRight,
  Download,
  Volume2
} from 'lucide-react';
import { motion, AnimatePresence, useScroll, useSpring } from 'motion/react';
import { GoogleGenAI, Modality } from "@google/genai";

const TypingText = ({ text, className }: { text: string; className?: string }) => {
  const [displayText, setDisplayText] = useState('');
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    setDisplayText('');
    setCurrentIndex(0);
  }, [text]);

  useEffect(() => {
    if (currentIndex < text.length) {
      const timeout = setTimeout(() => {
        setDisplayText(prev => prev + text[currentIndex]);
        setCurrentIndex(prev => prev + 1);
      }, 50);
      return () => clearTimeout(timeout);
    }
  }, [currentIndex, text]);

  return (
    <span className={className}>
      {displayText}
      <motion.span
        animate={{ opacity: [1, 0] }}
        transition={{ duration: 0.8, repeat: Infinity, ease: "steps(2)" }}
        className="inline-block w-0.5 h-5 ml-1 bg-teal-500 align-middle"
      />
    </span>
  );
};

interface Medication {
  name: string;
  dosage: string;
  frequency: string;
  duration: string;
  notes: string[];
  purpose: string;
}

interface JargonPair {
  jargon: string;
  simple: string;
}

interface SideEffect {
  medication: string;
  effect: string;
  severity: 'MILD' | 'MODERATE' | 'SEVERE';
}

interface AnalysisResult {
  diagnosis: string;
  medications: Medication[];
  side_effects: SideEffect[];
  followup: string[];
  family_summary: string;
  original_vs_simple: JargonPair[];
  confidence_score: number; // 0 to 100
  is_medical_document: boolean;
  error?: string;
}

interface UserSession {
  email: string;
  isAuthenticated: boolean;
}

const STEPS = {
  EN: [
    "Validating Document Type...",
    "Scanning Handwriting & Text...",
    "Simplifying Medical Jargon...",
    "Safety Check & Verification...",
    "Finalizing Your Dashboard"
  ],
  HI: [
    "दस्तावेज़ प्रकार की पुष्टि की जा रही है...",
    "हस्तलेखन और पाठ को स्कैन किया जा रहा है...",
    "चिकित्सा शब्दावली को सरल बनाया जा रहा है...",
    "सुरक्षा जांच और सत्यापन...",
    "आपका डैशबोर्ड तैयार किया जा रहा है"
  ]
};

const TRANSLATIONS = {
  EN: {
    analyses: "Analyses",
    demo: "Demo",
    logout: "Logout",
    heroTitle: "Understand Your Medical Records",
    heroHighlight: "Instantly",
    heroSub: "Turning medical confusion into clarity...",
    uploadTab: "Upload File",
    manualTab: "Type Prescription",
    uploadPrompt: "Click to upload or drag and drop",
    uploadSub: "PDF, JPG, or PNG (Max 10MB)",
    manualPlaceholder: "Type your medicine names or paste your prescription text here...",
    patientAge: "Patient Age",
    caregiverMode: "Caregiver Mode",
    caregiverSub: "Optimizes summary for elderly care instructions.",
    simplifyBtn: "Simplify Now",
    analyzingBtn: "Analyzing...",
    dashboardTitle: "Your Health Dashboard",
    reliability: "Reliability",
    printSummary: "Print Summary",
    listenSummary: "Listen to Summary",
    shareSummary: "Share Summary",
    diagnosisTitle: "Diagnosis Breakdown",
    summaryTitle: "Simplified Summary",
    followupTitle: "Follow-Up Instructions",
    medicationTitle: "Medication Schedule",
    jargonTitle: "Medical Jargon vs Plain Language",
    doctorWrote: "What Doctor Wrote",
    plainLanguage: "Plain Language",
    followupActions: "Follow-Up Actions",
    watchOut: "Watch Out For",
    medName: "Medication",
    medDose: "Dose",
    medFreq: "How Often",
    medDur: "Duration",
    medNotes: "Notes",
    disclaimer: "Dosewise is an AI assistant for informational purposes only. Always consult your doctor for medical decisions.",
    builtFor: "Built for IAR Udaan Hackathon 2026",
    uncertainReading: "Uncertain Reading",
    mainDiagnosis: "Main Diagnosis",
    shareSuccess: "Optimized summary copied! Paste it in WhatsApp.",
    shareHeader: "*Dosewise Health Summary*",
    shareDiagnosis: "*Diagnosis:*",
    shareSummaryLabel: "*Summary:*",
    shareMedications: "*Medications:*",
    shareNextSteps: "*Next Steps:*",
    shareFooter: "_Generated by Dosewise AI_",
    welcome: "Welcome to Dosewise",
    welcomeSub: "Your AI-powered medical record simplifier.",
    demoSecurity: "Demo Security:",
    demoSub: "This is a prototype. Passwords are hashed locally for simulation. Use",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    signIn: "Sign In",
    createAccount: "Create Account",
    noAccount: "Don't have an account? Register",
    hasAccount: "Already have an account? Sign In",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    verificationWarning: "Important: Some medicine names could not be fully verified. Please double-check with the physical prescription and consult your pharmacist or doctor before taking any medication."
  },
  HI: {
    analyses: "विश्लेषण",
    demo: "डेमो",
    logout: "लॉगआउट",
    heroTitle: "अपने मेडिकल रिकॉर्ड को",
    heroHighlight: "तुरंत समझें",
    heroSub: "चिकित्सा संबंधी भ्रम को स्पष्टता में बदलना...",
    uploadTab: "फ़ाइल अपलोड करें",
    manualTab: "नुस्खा टाइप करें",
    uploadPrompt: "अपलोड करने के लिए क्लिक करें या खींचें और छोड़ें",
    uploadSub: "PDF, JPG, या PNG (अधिकतम 10MB)",
    manualPlaceholder: "अपनी दवाओं के नाम टाइप करें या यहाँ अपना नुस्खा पेस्ट करें...",
    patientAge: "मरीज की उम्र",
    caregiverMode: "देखभालकर्ता मोड",
    caregiverSub: "बुजुर्गों की देखभाल के निर्देशों के लिए सारांश को अनुकूलित करता है।",
    simplifyBtn: "अभी सरल करें",
    analyzingBtn: "विश्लेषण किया जा रहा है...",
    dashboardTitle: "आपका स्वास्थ्य डैशबोर्ड",
    reliability: "विश्वसनीयता",
    printSummary: "सारांश प्रिंट करें",
    listenSummary: "सारांश सुनें",
    shareSummary: "सारांश साझा करें",
    diagnosisTitle: "निदान विवरण",
    summaryTitle: "सरलीकृत सारांश",
    followupTitle: "फॉलो-अप निर्देश",
    medicationTitle: "दवा की समय सारणी",
    jargonTitle: "चिकित्सा शब्दावली बनाम सरल भाषा",
    doctorWrote: "डॉक्टर ने क्या लिखा",
    plainLanguage: "सरल भाषा",
    followupActions: "फॉलो-अप क्रियाएं",
    watchOut: "ध्यान दें",
    medName: "दवा",
    medDose: "खुराक",
    medFreq: "कितनी बार",
    medDur: "अवधि",
    medNotes: "नोट्स",
    disclaimer: "डोज़वाइज़ केवल सूचनात्मक उद्देश्यों के लिए एक AI सहायक है। चिकित्सा निर्णयों के लिए हमेशा अपने डॉक्टर से परामर्श करें।",
    builtFor: "IAR उड़ान हैकाथॉन 2026 के लिए निर्मित",
    uncertainReading: "अनिश्चित रीडिंग",
    mainDiagnosis: "मुख्य निदान",
    shareSuccess: "अनुकूलित सारांश कॉपी किया गया! इसे व्हाट्सएप में पेस्ट करें।",
    shareHeader: "*डोज़वाइज़ स्वास्थ्य सारांश*",
    shareDiagnosis: "*निदान:*",
    shareSummaryLabel: "*सारांश:*",
    shareMedications: "*दवाएं:*",
    shareNextSteps: "*अगले कदम:*",
    shareFooter: "_डोज़वाइज़ AI द्वारा निर्मित_",
    welcome: "डोज़वाइज़ में आपका स्वागत है",
    welcomeSub: "आपका AI-संचालित मेडिकल रिकॉर्ड सरलीकरण सहायक।",
    demoSecurity: "डेमो सुरक्षा:",
    demoSub: "यह एक प्रोटोटाइप है। पासवर्ड सिमुलेशन के लिए स्थानीय रूप से हैश किए जाते हैं। परीक्षण के लिए उपयोग करें:",
    emailLabel: "ईमेल पता",
    passwordLabel: "पासवर्ड",
    signIn: "साइन इन करें",
    createAccount: "खाता बनाएं",
    noAccount: "क्या आपके पास खाता नहीं है? रजिस्टर करें",
    hasAccount: "क्या आपके पास पहले से खाता है? साइन इन करें",
    darkMode: "डार्क मोड",
    lightMode: "लाइट मोड",
    verificationWarning: "महत्वपूर्ण: कुछ दवाओं के नाम पूरी तरह से सत्यापित नहीं किए जा सके। कृपया भौतिक नुस्खे के साथ दोबारा जांचें और कोई भी दवा लेने से पहले अपने फार्मासिस्ट या डॉक्टर से परामर्श करें।"
  }
};

const SAMPLE_DATA: AnalysisResult = {
  diagnosis: "Acne Vulgaris (Facial and Back Acne)",
  medications: [
    { name: "Tab Doxy", dosage: "Not specified", frequency: "Not specified", duration: "Not specified", notes: ["Take after meals.", "Avoid direct sunlight while on this medication."], purpose: "Antibiotic for skin" },
    { name: "Tab Metrogy", dosage: "400 mg", frequency: "Not specified", duration: "Not specified", notes: ["Do not consume alcohol.", "Take with plenty of water."], purpose: "Antibacterial" },
    { name: "Tab vit-A", dosage: "Not specified", frequency: "Not specified", duration: "Not specified", notes: ["Take at night.", "Not for use during pregnancy."], purpose: "Skin health" },
    { name: "Peesol 2.5% Gel", dosage: "Not applicable", frequency: "Apply as directed", duration: "Not specified", notes: ["Apply on chest and back.", "Wash hands after application."], purpose: "Topical treatment" }
  ],
  side_effects: [
    { medication: "Tab Doxy", effect: "Increased sensitivity to sunlight, stomach upset.", severity: "MODERATE" },
    { medication: "Tab Metrogy", effect: "Nausea, metallic taste in mouth.", severity: "MILD" }
  ],
  followup: [
    "Schedule a follow-up visit with the doctor.",
    "Monitor acne lesions for improvement or worsening.",
    "Report any new or concerning side effects.",
    "Ensure consistent application of Peesol Gel.",
    "Complete the full course of prescribed oral medications."
  ],
  family_summary: "The patient, an 18-year-old male, has been diagnosed with acne on his face and back. He needs to follow a regimen of oral antibiotics and topical gels. It's important to take the tablets after meals and apply the gel as directed.",
  original_vs_simple: [
    { jargon: "The patient, an 18-year-old male, has been diagnosed with acne lesions present on his face and back.", simple: "The 18-year-old boy has acne on his face and back." },
    { jargon: "Tab Doxy Not specified Not specified for Not specified - Take after meals.", simple: "Take Tab Doxy (Not specified) Not specified. Take after meals. Continue for Not specified." },
    { jargon: "Tab Metrogy 400 mg Not specified for Not specified - Not specified.", simple: "Take Tab Metrogy (400 mg) Not specified. Not specified. Continue for Not specified." }
  ],
  confidence_score: 95,
  is_medical_document: true
};

export default function App() {
  const [session, setSession] = useState<UserSession | null>(null);
  const [authMode, setAuthMode] = useState<'login' | 'register'>('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isAuthLoading, setIsAuthLoading] = useState(false);

  const [file, setFile] = useState<File | null>(null);
  const [manualText, setManualText] = useState<string>('');
  const [inputType, setInputType] = useState<'upload' | 'manual'>('upload');
  const [age, setAge] = useState<string>('');
  const [language, setLanguage] = useState<'EN' | 'HI'>('EN');
  const [darkMode, setDarkMode] = useState<boolean>(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [currentStep, setCurrentStep] = useState(-1);
  const [progress, setProgress] = useState(0);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isCaregiverMode, setIsCaregiverMode] = useState(false);
  const [stats, setStats] = useState({ analysisCount: 0, errorCount: 0 });
  const fileInputRef = useRef<HTMLInputElement>(null);

  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });

  const containerVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: 0.6,
        staggerChildren: 0.1,
        ease: "easeOut"
      }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  useEffect(() => {
    const savedSession = localStorage.getItem('medbuddy_session');
    if (savedSession) {
      setSession(JSON.parse(savedSession));
    }
    fetchStats();

    const savedDarkMode = localStorage.getItem('dosewise_dark_mode');
    if (savedDarkMode === 'true') {
      setDarkMode(true);
      document.documentElement.classList.add('dark');
    }
  }, []);

  const toggleDarkMode = () => {
    const newMode = !darkMode;
    setDarkMode(newMode);
    localStorage.setItem('dosewise_dark_mode', String(newMode));
    if (newMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  const fetchStats = async () => {
    try {
      const res = await fetch('/api/stats');
      const data = await res.json();
      setStats(data);
    } catch (e) {
      console.error("Failed to fetch stats", e);
    }
  };

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsAuthLoading(true);
    // Simulate hashing and backend delay
    await new Promise(r => setTimeout(r, 1000));
    
    // DEMO AUTH: In a real app, this would be a backend call
    const mockHash = (str: string) => btoa(str).split('').reverse().join('');
    
    if (authMode === 'register') {
      localStorage.setItem(`user_${email}`, JSON.stringify({ email, passwordHash: mockHash(password) }));
      alert("Registration successful! (Demo Mode)");
      setAuthMode('login');
    } else {
      const userData = localStorage.getItem(`user_${email}`);
      if (userData) {
        const { passwordHash } = JSON.parse(userData);
        if (passwordHash === mockHash(password)) {
          const newSession = { email, isAuthenticated: true };
          setSession(newSession);
          localStorage.setItem('medbuddy_session', JSON.stringify(newSession));
        } else {
          setError("Invalid password (Demo)");
        }
      } else if (email === 'demo@example.com' && password === 'demo123') {
        const newSession = { email, isAuthenticated: true };
        setSession(newSession);
        localStorage.setItem('medbuddy_session', JSON.stringify(newSession));
      } else {
        setError("User not found. Try demo@example.com / demo123");
      }
    }
    setIsAuthLoading(false);
  };

  const handleLogout = () => {
    setSession(null);
    localStorage.removeItem('medbuddy_session');
  };

  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        const base64String = (reader.result as string).split(',')[1];
        resolve(base64String);
      };
      reader.onerror = error => reject(error);
    });
  };

  const simulateProgress = async () => {
    setProgress(0);
    const steps = STEPS[language];
    for (let i = 0; i < steps.length; i++) {
      setCurrentStep(i);
      const stepProgress = (i + 1) * (100 / steps.length);
      // Smooth progress increment
      const start = progress;
      for(let p = start; p <= stepProgress; p += 5) {
        setProgress(p);
        await new Promise(r => setTimeout(r, 150));
      }
    }
  };

  const handleDemoMode = async () => {
    setError(null);
    setResult(null);
    setIsAnalyzing(true);
    await simulateProgress();
    setResult(SAMPLE_DATA);
    setIsAnalyzing(false);
    setCurrentStep(-1);
    setProgress(100);
  };

  const analyzeDocument = async () => {
    if (inputType === 'upload' && !file) {
      setError("Please upload a document first.");
      return;
    }
    if (inputType === 'manual' && !manualText.trim()) {
      setError("Please enter your prescription details.");
      return;
    }

    // Basic medical keyword check for manual text
    if (inputType === 'manual') {
      const medicalKeywords = ['mg', 'tablet', 'capsule', 'dose', 'daily', 'twice', 'prescription', 'dr', 'patient', 'diagnosis', 'syrup', 'ml', 'gel', 'ointment'];
      const hasKeywords = medicalKeywords.some(k => manualText.toLowerCase().includes(k));
      if (!hasKeywords && manualText.split(' ').length > 5) {
        setError("This doesn't look like a medical prescription. Please include medicine names or dosages.");
        return;
      }
    }

    setError(null);
    setResult(null);
    setIsAnalyzing(true);
    
    try {
      let parts: any[] = [];
      
      if (inputType === 'upload' && file) {
        const base64Data = await fileToBase64(file);
        const mimeType = file.type;
        parts.push({
          inlineData: {
            data: base64Data,
            mimeType: mimeType
          }
        });
      } else {
        parts.push({ text: `MANUAL PRESCRIPTION TEXT: ${manualText}` });
      }

      const progressPromise = simulateProgress();

      const systemPrompt = `You are Dosewise, a specialized medical document parser for the IAR Udaan Hackathon 2026. 
TASK: Extract data from the provided image/PDF or manual text with 100% accuracy. 
STRICT RULES:
1. Do NOT suggest new treatments or change prescribed medications.
2. Medication dosages must be 100% verbatim from the input.
3. If information is missing, use 'Not specified'.
4. If the input is NOT a medical record or prescription, return {"is_medical_document": false, "error": "Invalid document type"}.
5. HANDWRITING & CLARITY: Prescriptions often have difficult handwriting. Use your medical knowledge and the context of the diagnosis to accurately identify medication names and dosages. 
6. MEDICINE VERIFICATION: Cross-reference every extracted medication name with your internal medical database. 
   - If a name is clearly legible but doesn't match a known medication, flag it as "[Unverified Name]".
   - If a name is partially illegible, use the surrounding context to infer the most likely medical term. 
   - If you are uncertain about a specific name, append "[Uncertain]" to the name (e.g., "Amoxicillin [Uncertain]"). 
   - If you suspect a misread, add a note: "[Potential misread due to handwriting]" in the 'notes' array.
   - NEVER hallucinate or invent medicine names. If you can't read it, say "Illegible".
7. LANGUAGE RULES: 
   - CURRENT LANGUAGE: ${language === 'HI' ? 'HINDI' : 'ENGLISH'}.
   - If language is HINDI, provide ALL explanations, summaries, and instructions in STRICT HINDI.
   - Keep ONLY medicine names in English.
   - Use correct Hindi punctuation (। instead of .).
8. Output ONLY a JSON object with these keys: 
   - diagnosis: string. If a specific diagnosis is not found, provide a simple, one-sentence explanation of what the prescribed medications are collectively for (e.g., "Medications for managing high blood pressure and cholesterol").
   - medications: array of {name, dosage, frequency, duration, notes, purpose}
     * name: Medication name. Append "[Uncertain]" or "[Unverified Name]" if applicable.
     * duration: Extract how long to take (e.g., '7 days'). If not found, 'Not specified'.
     * notes: array of strings. Extract ALL detailed instructions. CRITICAL: Translate medical instructions into very simple, plain language (e.g., instead of 'bid', use 'twice a day'; instead of 'pc', use 'after meals'). This is the most important part for the user.
   - side_effects: array of {medication, effect, severity (MILD/MODERATE/SEVERE)}
   - followup: array of strings
   - family_summary: string
   - original_vs_simple: array of {jargon, simple}
   - confidence_score: number (0-100 based on text clarity)
   - is_medical_document: boolean
9. Context: Patient age is ${age || 'Not specified'}. Adapt the 'family_summary' tone for this age group. ${isCaregiverMode ? 'Tone: Caregiver-focused, clear instructions for elderly care.' : ''}`;

      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });
      const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: [
          {
            parts: [
              { text: systemPrompt },
              ...parts
            ]
          }
        ],
        config: {
          responseMimeType: "application/json"
        }
      });

      if (!response.text) {
        throw new Error("Failed to get response from AI.");
      }

      const parsedResult = JSON.parse(response.text) as AnalysisResult;

      // Strict Validation
      if (!parsedResult.is_medical_document) {
        throw new Error("The uploaded document does not appear to be a medical record or prescription.");
      }

      if (!parsedResult.diagnosis || !parsedResult.medications) {
        throw new Error("Failed to extract essential medical information. Please try a clearer image.");
      }

      await progressPromise;
      setResult(parsedResult);
      fetchStats();
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Failed to analyze document. Please ensure it's a clear medical record.");
    } finally {
      setIsAnalyzing(false);
      setCurrentStep(-1);
      setProgress(0);
    }
  };

  const handleTTS = async () => {
    if (!result || isSpeaking) return;
    
    setIsSpeaking(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      const prompt = `Read this medical summary clearly in ${language === 'HI' ? 'Hindi' : 'English'}:
      Diagnosis: ${result.diagnosis}.
      Summary: ${result.family_summary}.
      Medications: ${result.medications.map(m => `${m.name}, ${m.dosage}`).join(', ')}.
      Next steps: ${result.followup.join(', ')}.`;

      const response = await ai.models.generateContent({
        model: "gemini-2.5-flash-preview-tts",
        contents: [{ parts: [{ text: prompt }] }],
        config: {
          responseModalities: [Modality.AUDIO],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: language === 'HI' ? 'Kore' : 'Zephyr' },
            },
          },
        },
      });

      const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
      if (base64Audio) {
        // Gemini TTS returns raw 16-bit PCM data at 24kHz
        const binaryString = atob(base64Audio);
        const bytes = new Uint8Array(binaryString.length);
        for (let i = 0; i < binaryString.length; i++) {
          bytes[i] = binaryString.charCodeAt(i);
        }

        const audioContext = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 24000 });
        
        // Convert 16-bit PCM to Float32
        const int16Data = new Int16Array(bytes.buffer);
        const float32Data = new Float32Array(int16Data.length);
        for (let i = 0; i < int16Data.length; i++) {
          float32Data[i] = int16Data[i] / 32768.0;
        }

        const audioBuffer = audioContext.createBuffer(1, float32Data.length, 24000);
        audioBuffer.getChannelData(0).set(float32Data);

        const source = audioContext.createBufferSource();
        source.buffer = audioBuffer;
        source.connect(audioContext.destination);
        source.onended = () => {
          setIsSpeaking(false);
          audioContext.close();
        };
        source.start();
      } else {
        setIsSpeaking(false);
      }
    } catch (error) {
      console.error("TTS error:", error);
      setIsSpeaking(false);
    }
  };

  const copyToWhatsApp = () => {
    if (!result) return;
    const t = TRANSLATIONS[language];
    const text = `${t.shareHeader}\n\n${t.shareDiagnosis} ${result.diagnosis}\n\n${t.shareSummaryLabel} ${result.family_summary}\n\n${t.shareMedications}\n${result.medications.map(m => `- ${m.name}: ${m.dosage} (${m.frequency})`).join('\n')}\n\n${t.shareNextSteps} ${result.followup.join(', ')}\n\n${t.shareFooter}`;
    navigator.clipboard.writeText(text);
    alert(t.shareSuccess);
  };

  if (!session) {
    const t = TRANSLATIONS[language];
    return (
      <div className={`min-h-screen flex items-center justify-center p-4 transition-colors duration-300 ${darkMode ? 'bg-slate-950' : 'bg-slate-50'}`}>
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="bg-white dark:bg-slate-900 p-8 rounded-[2.5rem] border border-slate-200 dark:border-slate-800 shadow-xl max-w-md w-full"
        >
          <div className="flex flex-col items-center mb-8">
            <div className="bg-teal-600 p-4 rounded-2xl mb-4 shadow-lg shadow-teal-200 dark:shadow-teal-900/20">
              <Stethoscope className="text-white w-8 h-8" />
            </div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">{t.welcome}</h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm mt-2 text-center">
              {t.welcomeSub}
            </p>
          </div>

          <div className="bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30 p-4 rounded-2xl mb-6 flex items-start gap-3">
            <ShieldAlert className="w-5 h-5 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
            <p className="text-xs text-amber-700 dark:text-amber-300 leading-relaxed">
              <span className="font-bold">{t.demoSecurity}</span> {t.demoSub} <span className="font-mono bg-amber-100 dark:bg-amber-900/40 px-1">demo@example.com / demo123</span> to test.
            </p>
          </div>

          <form onSubmit={handleAuth} className="space-y-4">
            <div>
              <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2 ml-1">{t.emailLabel}</label>
              <div className="relative">
                <User className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input 
                  type="email" 
                  required
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl focus:ring-2 focus:ring-teal-500 outline-none transition-all text-slate-900 dark:text-white"
                  placeholder="name@example.com"
                />
              </div>
            </div>
            <div>
              <label className="block text-xs font-bold text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2 ml-1">{t.passwordLabel}</label>
              <div className="relative">
                <Lock className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
                <input 
                  type="password" 
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full pl-12 pr-4 py-3 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl focus:ring-2 focus:ring-teal-500 outline-none transition-all text-slate-900 dark:text-white"
                  placeholder="••••••••"
                />
              </div>
            </div>

            {error && <p className="text-xs text-red-600 dark:text-red-400 font-medium ml-1">{error}</p>}

            <button 
              disabled={isAuthLoading}
              className="w-full py-4 bg-teal-600 text-white rounded-2xl font-bold hover:bg-teal-700 transition-all shadow-lg shadow-teal-100 dark:shadow-teal-900/20 flex items-center justify-center gap-2"
            >
              {isAuthLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : <ArrowRight className="w-5 h-5" />}
              {authMode === 'login' ? t.signIn : t.createAccount}
            </button>
          </form>

          <div className="mt-6 text-center">
            <button 
              onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}
              className="text-sm font-semibold text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300"
            >
              {authMode === 'login' ? t.noAccount : t.hasAccount}
            </button>
          </div>
        </motion.div>
      </div>
    );
  }

  return (
    <div className={`min-h-screen font-sans selection:bg-teal-500/30 transition-all duration-700 ${darkMode ? 'bg-slate-950 text-slate-200' : 'bg-slate-50 text-slate-800'}`}>
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute inset-0 hud-grid animate-grid-move opacity-30" />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-teal-500/5 dark:to-teal-500/10" />
      </div>

      <div className="relative z-10">
        {/* Navigation */}
        <nav className="sticky top-0 z-50 no-print backdrop-blur-xl border-b border-teal-500/10 dark:border-teal-500/20">
          <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
            <motion.div 
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              className="flex items-center gap-3 group cursor-pointer"
              onClick={() => { setResult(null); setFile(null); setManualText(''); }}
            >
              <div className="bg-teal-600 p-2.5 rounded-xl shadow-lg shadow-teal-500/20 group-hover:scale-110 transition-transform">
                <Stethoscope className="text-white w-6 h-6" />
              </div>
              <span className="text-2xl font-black tracking-tighter text-slate-900 dark:text-white group-hover:neon-text transition-all">DOSEWISE<span className="text-teal-500">.</span></span>
            </motion.div>
            <div className="flex items-center gap-4">
              <div className="hidden sm:flex items-center gap-2 text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mr-4 font-mono">
                <Activity className="w-4 h-4" />
                {stats.analysisCount} {TRANSLATIONS[language].analyses}
              </div>
              
              {/* Dark Mode Toggle */}
              <button 
                onClick={toggleDarkMode}
                className="p-2 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 rounded-lg hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors border border-teal-500/10"
                title={darkMode ? TRANSLATIONS[language].lightMode : TRANSLATIONS[language].darkMode}
              >
                {darkMode ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
              </button>

              <button 
                onClick={handleDemoMode}
                className="text-sm font-medium text-teal-600 dark:text-teal-400 hover:text-teal-700 dark:hover:text-teal-300 flex items-center gap-1 transition-colors font-mono"
              >
                <Zap className="w-4 h-4" />
                {TRANSLATIONS[language].demo}
              </button>
              <div className="h-6 w-px bg-slate-200 dark:bg-slate-800" />
              <div className="flex items-center gap-2 bg-slate-100 dark:bg-slate-800 p-1 rounded-md border border-teal-500/10">
                <button 
                  onClick={() => setLanguage('EN')}
                  className={`px-3 py-1 text-xs font-bold rounded transition-all ${language === 'EN' ? 'bg-white dark:bg-slate-700 text-teal-600 dark:text-teal-400 shadow-sm neon-border' : 'text-slate-500'}`}
                >
                  EN
                </button>
                <button 
                  onClick={() => setLanguage('HI')}
                  className={`px-3 py-1 text-xs font-bold rounded transition-all ${language === 'HI' ? 'bg-white dark:bg-slate-700 text-teal-600 dark:text-teal-400 shadow-sm neon-border' : 'text-slate-500'}`}
                >
                  HI
                </button>
              </div>
              <div className="h-6 w-px bg-slate-200 dark:bg-slate-800" />
              <button 
                onClick={handleLogout}
                className="p-2 text-slate-400 hover:text-red-500 transition-colors"
                title={TRANSLATIONS[language].logout}
              >
                <LogOut className="w-5 h-5" />
              </button>
            </div>
          </div>
        </nav>

      <main className="max-w-4xl mx-auto px-4 py-8 sm:px-6 lg:px-8 relative z-10">
        {/* Animated Background Gradient */}
        <div className="fixed inset-0 -z-10 overflow-hidden pointer-events-none">
          <div className="absolute inset-0 bg-gradient-to-br from-teal-50/50 via-white to-sky-50/50 dark:from-teal-950/20 dark:via-slate-950 dark:to-sky-950/20 animate-gradient-shift" />
          <div className="absolute top-[-10%] left-[-10%] w-[45%] h-[45%] rounded-full bg-teal-400/15 blur-[120px] animate-blob" />
          <div className="absolute bottom-[-10%] right-[-10%] w-[45%] h-[45%] rounded-full bg-sky-400/15 blur-[120px] animate-blob" />
          <div className="absolute top-[20%] right-[10%] w-[35%] h-[35%] rounded-full bg-emerald-400/10 blur-[100px] animate-blob" />
          <div className="absolute bottom-[20%] left-[10%] w-[30%] h-[30%] rounded-full bg-indigo-400/10 blur-[100px] animate-blob" />
          
          {/* Scanning Line */}
          <div className="absolute inset-0 opacity-10 dark:opacity-20 pointer-events-none">
            <div className="w-full h-[2px] bg-teal-500 animate-scan shadow-[0_0_15px_rgba(20,184,166,1)]" />
          </div>
        </div>

        {/* Hero Section */}
        <motion.section 
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="text-center mb-16 no-print relative"
        >
          {/* Floating Icons */}
          <div className="absolute inset-0 pointer-events-none overflow-visible">
            <motion.div 
              animate={{ y: [0, -25, 0], rotate: [0, 8, 0] }}
              transition={{ duration: 7, repeat: Infinity, ease: "easeInOut" }}
              className="absolute top-0 left-[2%] text-teal-500/40"
            >
              <Activity className="w-16 h-16" />
            </motion.div>
            <motion.div 
              animate={{ y: [0, 25, 0], rotate: [0, -12, 0] }}
              transition={{ duration: 8, repeat: Infinity, ease: "easeInOut", delay: 1.5 }}
              className="absolute top-24 right-[8%] text-sky-500/40"
            >
              <Pill className="w-14 h-14" />
            </motion.div>
            <motion.div 
              animate={{ scale: [1, 1.25, 1], y: [0, -20, 0] }}
              transition={{ duration: 9, repeat: Infinity, ease: "easeInOut", delay: 3 }}
              className="absolute bottom-4 left-[12%] text-emerald-500/40"
            >
              <Plus className="w-12 h-12" />
            </motion.div>
          </div>

          <motion.div variants={itemVariants}>
            <h1 className="text-5xl md:text-6xl font-extrabold text-slate-900 dark:text-white mb-6 tracking-tight leading-tight">
              {TRANSLATIONS[language].heroTitle} <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-600 to-sky-600 dark:from-teal-400 dark:to-sky-400 animate-gradient-shift">
                {TRANSLATIONS[language].heroHighlight}
              </span>
            </h1>
          </motion.div>
          
          <motion.div variants={itemVariants}>
            <p className="text-xl text-slate-600 dark:text-slate-400 max-w-2xl mx-auto leading-relaxed mb-8">
              <TypingText text={TRANSLATIONS[language].heroSub} />
            </p>
          </motion.div>
        </motion.section>

        {/* Input Section */}
        <motion.div 
          variants={containerVariants}
          initial="hidden"
          animate="visible"
          className="hud-panel rounded-[3rem] p-10 shadow-2xl border border-teal-500/20 mb-12 no-print"
        >
          <div className="flex flex-wrap gap-4 mb-10 p-2 bg-slate-100/50 dark:bg-slate-800/50 rounded-[2rem] border border-teal-500/10">
            <button 
              onClick={() => setInputType('upload')}
              className={`flex-1 flex items-center justify-center gap-3 py-4 px-6 rounded-[1.5rem] font-bold transition-all ${inputType === 'upload' ? 'bg-white dark:bg-slate-700 text-teal-600 dark:text-teal-400 shadow-xl neon-border' : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'}`}
            >
              <Upload className="w-5 h-5" />
              {TRANSLATIONS[language].uploadTab}
            </button>
            <button 
              onClick={() => setInputType('manual')}
              className={`flex-1 flex items-center justify-center gap-3 py-4 px-6 rounded-[1.5rem] font-bold transition-all ${inputType === 'manual' ? 'bg-white dark:bg-slate-700 text-teal-600 dark:text-teal-400 shadow-xl neon-border' : 'text-slate-500 hover:text-slate-700 dark:hover:text-slate-300'}`}
            >
              <FileText className="w-5 h-5" />
              {TRANSLATIONS[language].manualTab}
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="md:col-span-2 space-y-6">
              <AnimatePresence mode="wait">
                {inputType === 'upload' ? (
                  <motion.div 
                    key="upload"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    className="space-y-4"
                  >
                    <div 
                      onClick={() => fileInputRef.current?.click()}
                      onDragOver={(e) => e.preventDefault()}
                      onDrop={(e) => {
                        e.preventDefault();
                        const droppedFile = e.dataTransfer.files[0];
                        if (droppedFile) setFile(droppedFile);
                      }}
                      className={`relative group cursor-pointer border-2 border-dashed rounded-[2rem] p-12 transition-all flex flex-col items-center justify-center gap-4 h-80 ${file ? 'border-teal-500 bg-teal-50/30 dark:bg-teal-900/20' : 'border-slate-200 dark:border-slate-800 hover:border-teal-400 dark:hover:border-teal-600 bg-white/50 dark:bg-slate-900/50'}`}
                    >
                      <input 
                        type="file" 
                        ref={fileInputRef}
                        onChange={(e) => setFile(e.target.files?.[0] || null)}
                        className="hidden"
                        accept="image/*,application/pdf"
                      />
                      <div className={`p-6 rounded-3xl transition-all ${file ? 'bg-teal-500 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-400 group-hover:text-teal-500'}`}>
                        {file ? <CheckCircle2 className="w-10 h-10" /> : <Upload className="w-10 h-10" />}
                      </div>
                      <div className="text-center relative z-10">
                        <p className="text-lg font-bold text-slate-900 dark:text-white mb-1">
                          {file ? file.name : TRANSLATIONS[language].uploadPrompt}
                        </p>
                        <p className="text-sm text-slate-500 dark:text-slate-400">{TRANSLATIONS[language].uploadSub}</p>
                      </div>
                    </div>
                  </motion.div>
                ) : (
                  <motion.div 
                    key="manual"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 20 }}
                    className="space-y-4"
                  >
                    <textarea 
                      value={manualText}
                      onChange={(e) => setManualText(e.target.value)}
                      placeholder={TRANSLATIONS[language].manualPlaceholder}
                      className="w-full h-80 p-8 bg-white/50 dark:bg-slate-900/50 border-2 border-slate-200 dark:border-slate-800 rounded-[2rem] focus:ring-4 focus:ring-teal-500/10 focus:border-teal-500 outline-none transition-all text-lg resize-none"
                    />
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            <div className="space-y-6">
              <div className="bg-white/50 dark:bg-slate-900/50 p-8 rounded-[2rem] border border-slate-200 dark:border-slate-800">
                <label className="block text-xs font-black text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-4 font-mono">{TRANSLATIONS[language].patientAge}</label>
                <div className="relative">
                  <User className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400" />
                  <input 
                    type="number" 
                    min="0"
                    value={age}
                    onChange={(e) => {
                      const val = e.target.value;
                      if (val === '' || parseInt(val) >= 0) {
                        setAge(val);
                      }
                    }}
                    className="w-full pl-12 pr-4 py-4 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl focus:ring-2 focus:ring-teal-500 outline-none transition-all text-lg font-bold"
                    placeholder="25"
                  />
                </div>
              </div>

              <div className="bg-white/50 dark:bg-slate-900/50 p-8 rounded-[2rem] border border-slate-200 dark:border-slate-800">
                <div className="flex items-center justify-between mb-4">
                  <label className="text-xs font-black text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] font-mono">{TRANSLATIONS[language].caregiverMode}</label>
                  <button 
                    onClick={() => setIsCaregiverMode(!isCaregiverMode)}
                    className={`relative w-12 h-6 rounded-full transition-colors ${isCaregiverMode ? 'bg-teal-500' : 'bg-slate-200 dark:bg-slate-700'}`}
                  >
                    <motion.div 
                      animate={{ x: isCaregiverMode ? 24 : 4 }}
                      className="absolute top-1 w-4 h-4 rounded-full bg-white shadow-sm"
                    />
                  </button>
                </div>
                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed">{TRANSLATIONS[language].caregiverSub}</p>
              </div>
            </div>
          </div>

          <motion.button 
            whileHover={{ scale: 1.02, boxShadow: "0 20px 40px rgba(20, 184, 166, 0.2)" }}
            whileTap={{ scale: 0.98 }}
            disabled={isAnalyzing || (inputType === 'upload' ? !file : !manualText.trim())}
            onClick={analyzeDocument}
            className={`w-full py-5 rounded-[2rem] font-bold flex items-center justify-center gap-3 transition-all shadow-2xl mt-8 ${isAnalyzing || (inputType === 'upload' ? !file : !manualText.trim()) ? 'bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-600 cursor-not-allowed shadow-none' : 'bg-teal-600 text-white hover:bg-teal-700 neon-border'}`}
          >
            {isAnalyzing ? <Loader2 className="w-6 h-6 animate-spin" /> : <Zap className="w-6 h-6" />}
            <span className="text-lg">{isAnalyzing ? TRANSLATIONS[language].analyzingBtn : TRANSLATIONS[language].simplifyBtn}</span>
          </motion.button>
        </motion.div>

        {/* Error Message */}
        <AnimatePresence>
          {error && (
            <motion.div 
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-900/30 text-red-700 dark:text-red-400 p-4 rounded-xl mb-8 flex items-center justify-between gap-3 no-print"
            >
              <div className="flex items-center gap-3">
                <AlertCircle className="w-5 h-5 flex-shrink-0" />
                <p className="text-sm font-medium">{error}</p>
              </div>
              <button 
                onClick={analyzeDocument}
                className="p-2 hover:bg-red-100 dark:hover:bg-red-900/40 rounded-lg transition-colors"
                title="Retry"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Processing Steps */}
        <AnimatePresence>
          {isAnalyzing && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="hud-panel rounded-[2.5rem] p-10 shadow-2xl mb-12 no-print relative overflow-hidden border-teal-500/30"
            >
              {/* Scanning Line Overlay */}
              <div className="absolute inset-0 pointer-events-none z-20">
                <div className="w-full h-1 bg-teal-500/40 animate-scan shadow-[0_0_10px_rgba(20,184,166,0.5)]" />
              </div>
              
              <div className="flex items-center gap-6 mb-10 relative z-10">
                <div className="p-5 bg-teal-100 dark:bg-teal-900/40 rounded-3xl animate-pulse-teal neon-border">
                  <BrainCircuit className="w-10 h-10 text-teal-600 dark:text-teal-400" />
                </div>
                <div>
                  <h3 className="text-2xl font-extrabold text-slate-900 dark:text-white mb-1 neon-text">
                    {TRANSLATIONS[language].analyzingBtn}...
                  </h3>
                  <p className="text-slate-500 dark:text-slate-400 font-medium">Dosewise AI is processing your information</p>
                </div>
              </div>

              <div className="space-y-6 relative z-10">
                {STEPS[language].map((step, idx) => (
                  <motion.div 
                    key={idx}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ 
                      opacity: progress >= (idx + 1) * 20 ? 1 : 0.4,
                      x: 0,
                      scale: progress >= (idx + 1) * 20 ? 1.02 : 1
                    }}
                    className="flex items-center gap-5"
                  >
                    <div className={`w-10 h-10 rounded-2xl flex items-center justify-center transition-all duration-500 ${progress >= (idx + 1) * 20 ? 'bg-teal-500 text-white shadow-lg shadow-teal-500/20' : 'bg-slate-100 dark:bg-slate-800 text-slate-400'}`}>
                      {progress >= (idx + 1) * 20 ? <CheckCircle2 className="w-5 h-5" /> : <div className="w-2 h-2 rounded-full bg-current" />}
                    </div>
                    <span className={`text-lg font-bold transition-colors duration-500 ${progress >= (idx + 1) * 20 ? 'text-slate-900 dark:text-white' : 'text-slate-400'}`}>
                      {step}
                    </span>
                  </motion.div>
                ))}
              </div>

              {/* Progress Bar */}
              <div className="mt-12 h-3 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden relative">
                <motion.div 
                  initial={{ width: 0 }}
                  animate={{ width: `${progress}%` }}
                  className="absolute top-0 left-0 h-full bg-gradient-to-r from-teal-500 to-sky-500 shadow-lg shadow-teal-500/20"
                />
                <div className="absolute inset-0 animate-shimmer opacity-20" />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Results Dashboard */}
        <AnimatePresence>
          {result && !isAnalyzing && (
            <motion.div 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="space-y-8"
            >
              {/* Action Bar */}
              <motion.div 
                variants={itemVariants}
                className="flex flex-col md:flex-row md:items-center justify-between gap-6 no-print hud-panel p-6 rounded-[2.5rem] border-teal-500/20"
              >
                <div className="flex items-center gap-6">
                  <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight neon-text">{TRANSLATIONS[language].dashboardTitle}</h2>
                  <div className="flex flex-col gap-1.5 min-w-[160px]">
                    <div className="flex items-center justify-between text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500 font-mono">
                      <div className="flex items-center gap-1.5">
                        <ShieldCheck className="w-3.5 h-3.5" />
                        {TRANSLATIONS[language].reliability}
                      </div>
                      <span className={
                        result.confidence_score > 80 ? 'text-teal-600 dark:text-teal-400' :
                        result.confidence_score > 50 ? 'text-amber-600 dark:text-amber-400' :
                        'text-red-600 dark:text-red-400'
                      }>{result.confidence_score}%</span>
                    </div>
                    <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden border border-teal-500/10">
                      <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${result.confidence_score}%` }}
                        transition={{ duration: 1, ease: "easeOut" }}
                        className={`h-full rounded-full ${
                          result.confidence_score > 80 ? 'bg-teal-500 shadow-[0_0_12px_rgba(20,184,166,0.6)]' :
                          result.confidence_score > 50 ? 'bg-amber-500 shadow-[0_0_12px_rgba(245,158,11,0.6)]' :
                          'bg-red-500 shadow-[0_0_12px_rgba(239,68,68,0.6)]'
                        }`}
                      />
                    </div>
                  </div>
                </div>
                
                <div className="flex items-center gap-3">
                  <motion.button 
                    whileHover={{ scale: 1.05, y: -2 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={handleTTS}
                    disabled={isSpeaking}
                    className={`p-4 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-2xl shadow-lg border border-slate-100 dark:border-slate-700 hover:text-teal-600 dark:hover:text-teal-400 transition-colors ${isSpeaking ? 'opacity-50 cursor-not-allowed' : ''}`}
                    title={TRANSLATIONS[language].listenSummary}
                  >
                    {isSpeaking ? <Loader2 className="w-5 h-5 animate-spin" /> : <Volume2 className="w-5 h-5" />}
                  </motion.button>
                  <motion.button 
                    whileHover={{ scale: 1.05, y: -2 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={() => {
                      window.focus();
                      window.print();
                    }}
                    className="p-4 bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 rounded-2xl shadow-lg border border-slate-100 dark:border-slate-700 hover:text-teal-600 dark:hover:text-teal-400 transition-colors"
                    title={TRANSLATIONS[language].printSummary}
                  >
                    <Printer className="w-5 h-5" />
                  </motion.button>
                  <motion.button 
                    whileHover={{ scale: 1.05, y: -2 }}
                    whileTap={{ scale: 0.95 }}
                    onClick={copyToWhatsApp}
                    className="flex items-center gap-3 px-6 py-4 bg-teal-600 text-white rounded-2xl font-bold shadow-xl shadow-teal-600/20 hover:bg-teal-700 transition-all"
                  >
                    <Share2 className="w-5 h-5" />
                    {TRANSLATIONS[language].shareSummary}
                  </motion.button>
                </div>
              </motion.div>

              {/* Print Header */}
              <div className="hidden print-only text-center border-b-2 border-teal-600 pb-4 mb-8">
                <h1 className="text-3xl font-bold text-teal-900">Dosewise Simplified Guide</h1>
                <p className="text-slate-500">Generated on {new Date().toLocaleDateString()}</p>
              </div>

              {/* Diagnosis Card */}
              <motion.div 
                variants={itemVariants}
                className="hud-panel rounded-[2.5rem] p-10 relative overflow-hidden group border-teal-500/20"
              >
                <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:opacity-20 transition-opacity">
                  <Stethoscope className="w-32 h-32 text-teal-600" />
                </div>
                
                <div className="flex items-center gap-4 mb-8">
                  <div className="p-4 bg-teal-100 dark:bg-teal-900/40 rounded-2xl neon-border">
                    <Activity className="w-8 h-8 text-teal-600 dark:text-teal-400" />
                  </div>
                  <div>
                    <h3 className="text-sm font-black uppercase tracking-[0.2em] text-slate-400 dark:text-slate-500 font-mono">{TRANSLATIONS[language].mainDiagnosis}</h3>
                    <p className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight neon-text">{result.diagnosis}</p>
                  </div>
                </div>
              </motion.div>

              {/* Verification Warning */}
              {(result.confidence_score < 70 || result.medications.some(m => m.name.includes('[Unverified Name]') || m.name.includes('[Uncertain]'))) && (
                <motion.div 
                  variants={itemVariants}
                  className="bg-amber-50 dark:bg-amber-900/20 border-2 border-amber-200 dark:border-amber-900/30 p-8 rounded-[2.5rem] flex items-start gap-6 shadow-xl shadow-amber-200/20 dark:shadow-none no-print"
                >
                  <div className="p-4 bg-amber-100 dark:bg-amber-900/40 rounded-2xl">
                    <AlertTriangle className="w-8 h-8 text-amber-600 dark:text-amber-400" />
                  </div>
                  <div>
                    <h4 className="text-xl font-extrabold text-amber-900 dark:text-amber-200 mb-2">
                      {TRANSLATIONS[language].uncertainReading}
                    </h4>
                    <p className="text-amber-800 dark:text-amber-300 font-medium leading-relaxed">
                      {TRANSLATIONS[language].verificationWarning}
                    </p>
                  </div>
                </motion.div>
              )}

              {/* Summary & Follow-up Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <motion.div 
                  variants={itemVariants}
                  className="hud-panel rounded-[2.5rem] p-8 shadow-sm card group border-teal-500/20"
                >
                  <div className="flex items-center gap-4 mb-6">
                    <div className="p-3 bg-teal-100 dark:bg-teal-900/40 rounded-xl neon-border">
                      <FileText className="w-6 h-6 text-teal-600 dark:text-teal-400" />
                    </div>
                    <h3 className="text-xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].summaryTitle}</h3>
                  </div>
                  <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-lg font-medium">
                    {result.family_summary}
                  </p>
                </motion.div>

                <motion.div 
                  variants={itemVariants}
                  className="hud-panel rounded-[2.5rem] p-8 shadow-sm card group border-teal-500/20"
                >
                  <div className="flex items-center gap-4 mb-6">
                    <div className="p-3 bg-sky-100 dark:bg-sky-900/40 rounded-xl neon-border">
                      <Clock className="w-6 h-6 text-sky-600 dark:text-sky-400" />
                    </div>
                    <h3 className="text-xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].followupTitle}</h3>
                  </div>
                  <div className="space-y-4">
                    {result.followup.map((item, i) => (
                      <motion.div 
                        key={i} 
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.5 + (i * 0.1) }}
                        className="flex items-start gap-4 p-4 bg-slate-50/50 dark:bg-slate-800/50 rounded-2xl border border-slate-100 dark:border-slate-800 group/item hover:bg-white dark:hover:bg-slate-800 transition-all"
                      >
                        <div className="w-6 h-6 rounded-full bg-teal-100 dark:bg-teal-900/40 flex items-center justify-center flex-shrink-0 group-hover/item:bg-teal-500 transition-colors">
                          <div className="w-2 h-2 rounded-full bg-teal-500 group-hover/item:bg-white transition-colors" />
                        </div>
                        <p className="text-slate-600 dark:text-slate-400 font-medium">{item}</p>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              </div>

              {/* Medication Table */}
              <motion.div 
                variants={itemVariants}
                className="hud-panel rounded-[2.5rem] overflow-hidden border-teal-500/20 p-8 group"
              >
                <div className="flex items-center justify-between mb-8">
                  <div className="flex items-center gap-4">
                    <div className="bg-teal-100 dark:bg-teal-900/40 p-4 rounded-2xl neon-border">
                      <Pill className="w-8 h-8 text-teal-600 dark:text-teal-400" />
                    </div>
                    <h4 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].medicationTitle}</h4>
                  </div>
                  <div className="px-4 py-2 bg-teal-50 dark:bg-teal-900/20 rounded-full border border-teal-500/20">
                    <span className="text-xs font-black text-teal-600 dark:text-teal-400 uppercase tracking-widest font-mono">{result.medications.length} ITEMS</span>
                  </div>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full text-left border-separate border-spacing-y-4">
                    <thead>
                      <tr className="text-slate-400 dark:text-slate-500 text-[10px] font-black uppercase tracking-[0.2em] font-mono">
                        <th className="px-6 pb-2">{TRANSLATIONS[language].medName}</th>
                        <th className="px-6 pb-2">{TRANSLATIONS[language].medDose}</th>
                        <th className="px-6 pb-2">{TRANSLATIONS[language].medFreq}</th>
                        <th className="px-6 pb-2">{TRANSLATIONS[language].medDur}</th>
                        <th className="px-6 pb-2">{TRANSLATIONS[language].medNotes}</th>
                      </tr>
                    </thead>
                    <tbody className="space-y-4">
                      {result.medications.map((med, i) => (
                        <motion.tr 
                          key={i} 
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          transition={{ delay: 0.6 + (i * 0.1) }}
                          className="group/row"
                        >
                          <td className="px-6 py-6 bg-white/50 dark:bg-slate-800/50 rounded-l-3xl border-y border-l border-teal-500/10 group-hover/row:border-teal-500/30 transition-all">
                            <div className="flex flex-col gap-2">
                              <div className="flex items-center gap-3">
                                <div className="w-2 h-2 rounded-full bg-teal-500 shadow-[0_0_8px_rgba(20,184,166,0.6)]" />
                                <span className="text-lg font-bold text-slate-900 dark:text-white">{med.name.replace('[Uncertain]', '').trim()}</span>
                              </div>
                              {med.name.includes('[Uncertain]') && (
                                <div className="flex items-center gap-1.5 px-3 py-1 bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30 rounded-lg text-[10px] text-amber-700 dark:text-amber-400 font-black uppercase tracking-wider w-fit">
                                  <AlertTriangle className="w-3.5 h-3.5" />
                                  {TRANSLATIONS[language].uncertainReading}
                                </div>
                              )}
                            </div>
                          </td>
                          <td className="px-6 py-6 bg-white/50 dark:bg-slate-800/50 border-y border-teal-500/10 group-hover/row:border-teal-500/30 font-mono text-sm">
                            <span className="px-4 py-2 bg-slate-100 dark:bg-slate-800 rounded-xl text-slate-600 dark:text-slate-300 font-bold">
                              {med.dosage}
                            </span>
                          </td>
                          <td className="px-6 py-6 bg-white/50 dark:bg-slate-800/50 border-y border-teal-500/10 group-hover/row:border-teal-500/30 font-mono text-sm">
                            <div className="flex items-center gap-2 font-medium">
                              <Clock className="w-4 h-4 text-teal-500" />
                              {med.frequency}
                            </div>
                          </td>
                          <td className="px-6 py-6 bg-white/50 dark:bg-slate-800/50 border-y border-teal-500/10 group-hover/row:border-teal-500/30 font-mono text-sm">
                            <div className="flex items-center gap-2 font-medium">
                              <Calendar className="w-4 h-4 text-teal-500" />
                              {med.duration}
                            </div>
                          </td>
                          <td className="px-6 py-6 bg-white/50 dark:bg-slate-800/50 rounded-r-3xl border-y border-r border-teal-500/10 group-hover/row:border-teal-500/30">
                            <div className="flex flex-col gap-2">
                              {med.notes.map((note, idx) => (
                                <div key={idx} className={`flex items-start gap-2 p-2 rounded-xl transition-colors ${note.includes('[Uncertain') ? 'text-orange-600 dark:text-orange-400 bg-orange-50 dark:bg-orange-900/20 border border-orange-100 dark:border-orange-900/30' : 'hover:bg-white dark:hover:bg-slate-800'}`}>
                                  {note.includes('[Uncertain') ? (
                                    <AlertTriangle className="w-4 h-4 text-orange-500 dark:text-orange-400 mt-0.5 flex-shrink-0" />
                                  ) : (
                                    <Info className="w-4 h-4 text-teal-400 dark:text-teal-500 mt-0.5 flex-shrink-0" />
                                  )}
                                  <span className="leading-tight font-medium text-sm">{note}</span>
                                </div>
                              ))}
                            </div>
                          </td>
                        </motion.tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </motion.div>

              {/* Jargon Buster */}
              <motion.div 
                variants={itemVariants}
                className="hud-panel rounded-[2.5rem] p-10 border-teal-500/20 group"
              >
                <div className="flex items-center gap-4 mb-10">
                  <div className="bg-purple-50 dark:bg-purple-900/20 p-4 rounded-2xl neon-border">
                    <Languages className="w-8 h-8 text-purple-600 dark:text-purple-400" />
                  </div>
                  <h4 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].jargonTitle}</h4>
                </div>
                
                <div className="grid grid-cols-2 gap-10 mb-6 font-mono">
                  <div className="text-center">
                    <span className="px-6 py-2 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 text-[10px] font-black rounded-full uppercase tracking-[0.2em] border border-red-500/10">{TRANSLATIONS[language].doctorWrote}</span>
                  </div>
                  <div className="text-center">
                    <span className="px-6 py-2 bg-teal-50 dark:bg-teal-900/20 text-teal-600 dark:text-teal-400 text-[10px] font-black rounded-full uppercase tracking-[0.2em] border border-teal-500/10">{TRANSLATIONS[language].plainLanguage}</span>
                  </div>
                </div>

                <div className="space-y-6">
                  {result.original_vs_simple.map((pair, i) => (
                    <motion.div 
                      key={i} 
                      initial={{ opacity: 0, y: 10 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.7 + (i * 0.1) }}
                      className="grid grid-cols-2 gap-10 group/pair"
                    >
                      <div className="bg-red-50/30 dark:bg-red-900/10 p-6 rounded-3xl border border-red-100/50 dark:border-red-900/20 group-hover/pair:bg-red-50/50 transition-colors">
                        <p className="text-slate-900 dark:text-red-200 leading-relaxed font-bold italic">"{pair.jargon}"</p>
                      </div>
                      <div className="bg-teal-50/30 dark:bg-teal-900/10 p-6 rounded-3xl border border-teal-100/50 dark:border-teal-900/20 group-hover/pair:bg-teal-50/50 transition-colors relative">
                        <div className="absolute -left-5 top-1/2 -translate-y-1/2 w-10 h-10 bg-white dark:bg-slate-900 rounded-full border border-teal-500/20 flex items-center justify-center shadow-sm z-10 group-hover/pair:scale-110 transition-transform">
                          <ArrowRight className="w-5 h-5 text-teal-500" />
                        </div>
                        <p className="text-slate-900 dark:text-teal-200 leading-relaxed font-bold">{pair.simple}</p>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>

              {/* Bottom Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-8 print-grid">
                {/* Follow-up */}
                <motion.div 
                  variants={itemVariants}
                  className="hud-panel rounded-[2.5rem] p-8 border-teal-500/20 group"
                >
                  <div className="flex items-center gap-4 mb-8">
                    <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-2xl neon-border">
                      <ListTodo className="w-8 h-8 text-blue-600 dark:text-blue-400" />
                    </div>
                    <h4 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].followupActions}</h4>
                  </div>
                  <div className="space-y-4">
                    {result.followup.map((item, i) => (
                      <motion.div 
                        key={i} 
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.8 + (i * 0.1) }}
                        className="flex items-center gap-4 p-5 bg-white/50 dark:bg-slate-800/50 rounded-2xl border border-teal-500/10 group/item hover:border-teal-500/30 transition-all"
                      >
                        <motion.div 
                          whileHover={{ scale: 1.2 }}
                          className="w-6 h-6 rounded-lg border-2 border-slate-200 dark:border-slate-700 flex-shrink-0 flex items-center justify-center group-hover/item:border-teal-500 transition-colors"
                        >
                          <Check className="w-4 h-4 text-teal-500 opacity-0 group-hover/item:opacity-100 transition-opacity" />
                        </motion.div>
                        <span className="text-slate-600 dark:text-slate-300 font-bold">{item}</span>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>

                {/* Watch Out For */}
                <motion.div 
                  variants={itemVariants}
                  className="hud-panel rounded-[2.5rem] p-8 border-teal-500/20 group"
                >
                  <div className="flex items-center gap-4 mb-8">
                    <div className="bg-orange-50 dark:bg-orange-900/20 p-4 rounded-2xl neon-border">
                      <AlertTriangle className="w-8 h-8 text-orange-600 dark:text-orange-400" />
                    </div>
                    <h4 className="text-2xl font-extrabold text-slate-900 dark:text-white tracking-tight">{TRANSLATIONS[language].watchOut}</h4>
                  </div>
                  <div className="space-y-4">
                    {result.side_effects.map((effect, i) => (
                      <motion.div 
                        key={i} 
                        initial={{ opacity: 0, x: 10 }}
                        animate={{ opacity: 1, x: 0 }}
                        transition={{ delay: 0.8 + (i * 0.1) }}
                        className="p-6 bg-orange-50/30 dark:bg-orange-900/10 rounded-3xl border border-orange-500/10 relative group/effect hover:border-orange-500/30 transition-all"
                      >
                        <div className="flex justify-between items-start mb-3">
                          <h5 className="font-black text-slate-900 dark:text-white text-lg">{effect.medication}</h5>
                          <span className={`px-3 py-1 rounded-lg text-[10px] font-black tracking-wider font-mono ${
                            effect.severity === 'SEVERE' ? 'bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400' :
                            effect.severity === 'MODERATE' ? 'bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400' :
                            'bg-yellow-100 text-yellow-600 dark:bg-yellow-900/30 dark:text-yellow-400'
                          }`}>
                            {effect.severity}
                          </span>
                        </div>
                        <p className="text-orange-900/80 dark:text-orange-400/80 font-bold leading-relaxed">
                          {effect.effect}
                        </p>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              </div>

              {/* Disclaimer */}
              <motion.footer 
                variants={itemVariants}
                className="text-center text-xs text-slate-400 dark:text-slate-600 mt-16 pb-12 max-w-2xl mx-auto leading-relaxed font-mono"
              >
                <p className="font-medium">{TRANSLATIONS[language].disclaimer}</p>
                <div className="mt-4 flex items-center justify-center gap-2 no-print">
                  <div className="w-1 h-1 rounded-full bg-teal-500 shadow-[0_0_5px_rgba(20,184,166,0.5)]" />
                  <p className="font-bold tracking-[0.2em] uppercase text-[9px] neon-text">{TRANSLATIONS[language].builtFor}</p>
                  <div className="w-1 h-1 rounded-full bg-teal-500 shadow-[0_0_5px_rgba(20,184,166,0.5)]" />
                </div>
              </motion.footer>
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  </div>
);
}
